<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKcmlxzl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKcmlxzl/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKcmlxzl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKcmlxzl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKcmlxzl\appProdProjectContainer(array(
    'container.build_hash' => 'Kcmlxzl',
    'container.build_id' => '7c609006',
    'container.build_time' => 1560333616,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKcmlxzl');
